# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1615b8b7e7ebe3b8232cf8539dffccdc"
name = "booking-app-google-sheet"
application_url = "https://3b76bb818406.ngrok-free.app/"
embedded = true
handle = "booking-app-google-sheet"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,read_orders,write_orders,write_customers,read_customers,write_inventory,read_inventory,write_draft_orders,read_draft_orders"

[auth]
redirect_urls = [ "https://3b76bb818406.ngrok-free.app/api/auth" ]

[pos]
embedded = false
